version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: ct-web-app:latest
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    stdin_open: true
