export const defaultValueUsers = 200;
export const defaultValueInfectedUsers = defaultValueUsers / 10;
export const defaultValueEstablishments = 10;
export const defaultValueMobility = 3;
export const defaultValueDays = 60;
export const maxValueUsers = 500;
export const maxValueEstablishments = 50;
export const maxValueMobility = 25;
export const maxValueDays = 180;